version: '3.9'

services:
  db:
    container_name: oracle-db-service
    image: gvenzl/oracle-xe:latest
    ports:
      - "9445:1521"
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=test
      - APP_USER_PASSWORD=test
    healthcheck:
      test: [
        "CMD-SHELL",
        "echo \"SELECT open_mode FROM v\\$pdbs WHERE name='XEPDB1' AND open_mode='READ WRITE';\" \
         | sqlplus -s test/test@localhost:1521/XEPDB1 \
         | grep 'READ WRITE'"
      ]
      interval: 10s
      timeout: 5s
      retries: 12

  app:
    container_name: security-system-app
    image: fabiodinizdev/security-system:latest
    ports:
    - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_DRIVERCLASSNAME: oracle.jdbc.OracleDriver