services:
  oracle:
    image: 'gvenzl/oracle-free:latest'
    environment:
      ORACLE_PASSWORD: orcl_security
      APP_USER: user_oracle
      APP_USER_PASSWORD: pass_oracle
    ports:
      - '1521:1521'
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | sqlplus -s user_oracle/pass_oracle@//localhost:1521/XEPDB1"]
      interval: 10s
      retries: 10
